### ISSUE TITLE
Choose IDE for desktop app dev - chose VS CE 2017

### ISSUE THREAD

**Issue by moorecode** [eckersleyalexander/orienteering_live_results#12]
I think we should all use the same one as it will reduce issues down the line.

We basically have two options as I think the setup for others like sublime and vscode is complicated and not fully supported.

Options:
- Rider (JetBrains)
- Visual Studio

**Comment by moorecode** [comment]
My vote is for Rider, it seems to have very good cross platform config options and has full support for the kind of project we are doing.

**Comment by CGS-Matthew-Purcell** [comment]
Is Rider commercial (do you need to pay for the IDE)?

**Comment by CGS-Matthew-Purcell** [comment]
My _strong_ preference is Visual Studio Community 2017, to make it easiest for other people to compile and use the software (since it is open source, and VS is far more widely accepted than other IDEs).

**Comment by moorecode** [comment]
Very good point that I didn't think of, we get Rider for free as uni students but I think its quite expensive otherwise.

**Comment by CGS-Matthew-Purcell** [comment]
Yeah, I just looked at that on their website.

**Comment by CGS-Matthew-Purcell** [comment]
Crap, sorry. I thought the Close was Cancel
