### ISSUE TITLE
Choose web technology to be used in web front end

### ISSUE THREAD

**Issue by moorecode** [eckersleyalexander/orienteering_live_results#15]
We need to decide if we are going to use a framework like Angular or React, or just stick with vanilla HTML/CSS/JS.

**Comment by moorecode** [comment]
I think given the scope and size of the front end, as well as the level of interaction, that we should not use a framework.

**Comment by CGS-Matthew-Purcell** [comment]
I have had some good experiences with Vue.js. Much simpler than the behemoth of React and has reasonably sane documentation too. Just throwing that into the mix for consideration.

**Comment by moorecode** [comment]
@eckersleyalexander and @u5561865-drc Would be good to hear from you guys, if you have prior experience with something and would like to use that over the no framework approach.

**Comment by u5561865-drc** [comment]
I could really go either way on this one, I'll wait for @eckersleyalexander to weigh in too.
If we do go with a framework I'd agree with the suggestion of vue as it is pretty easy to get it up and running + having things like Components will be useful as there will be similar things displayed on each of the leaderboard/commentator/overlay displays.

**Comment by eckersleyalexander** [comment]
Not massively drawn to one thing or the other. Vue sounds fine?

**Comment by u5561865-drc** [comment]
I'll tentatively close this, with Vue being the framework of choice.
