### ISSUE TITLE
Internal web server solution (chose embedio)

### ISSUE THREAD

**Issue by moorecode** [eckersleyalexander/orienteering_live_results#18]
We need to decide on what to use for the internal web server

**Comment by moorecode** [comment]
I found this: 
https://github.com/pvginkel/NHttp

**Comment by u5561865-drc** [comment]
https://github.com/unosquare/embedio seems like a reasonably up-to-date/supported option

**Comment by moorecode** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener?redirectedfrom=MSDN&view=netframework-4.7.2 This is built in, but it seems to be quite low level. Maybe on of the higher abstraction ones will server us better.

**Comment by moorecode** [comment]
In favour of an active community, I saw we use embedio.

**Comment by CGS-Matthew-Purcell** [comment]
Don't forget you'll want to choose something that can support WebSockets or similar for constant updates of the front end.

**Comment by moorecode** [comment]
embedio supports websockets ✅
