### ISSUE TITLE
design desktop ap UI/appearance

### ISSUE THREAD

**Issue by ShamelessEnd** [eckersleyalexander/orienteering_live_results#48]
make a first iteration

**Comment by eckersleyalexander** [comment]
discussion with client, worked out what features need to be present: 
Competitor info: 
Course they are doing
What their status is i.e. have they finished?
Edit/delete provisional radio times
Display list of controls, be able to indicate which ones are radio controls
Import distance data (also be able to import distances manually)
Read only view of all the courses and which controls are radios being highlighted, classes
