### ISSUE TITLE
write module for reading dbisam dat files

### ISSUE THREAD

**Issue by ShamelessEnd** [eckersleyalexander/orienteering_live_results#67]

**Comment by ShamelessEnd** [comment]
class for reading dbisam files is now functioning in branch dbisamtest.
is currently in a seperate project - will need to integrate.
date/time timestamp fields still currently saved in raw (millisecond) form.

**Comment by ddrcloud** [comment]
where is lc_petra_db.exe ??
source code?
buy page?
