### ISSUE TITLE
Desktop App UI based on client feedback

### ISSUE THREAD

**Issue by eckersleyalexander** [eckersleyalexander/orienteering_live_results#76]
UI to include:
Competitor info: 
Course they are doing
What their status is i.e. have they finished?
Edit/delete provisional radio times
Display list of controls, be able to indicate which ones are radio controls
Import distance data (also be able to import distances manually)
Read only view of all the courses and which controls are radios being highlighted, classes

**Comment by ShamelessEnd** [comment]
from client meeting:
https://docs.google.com/document/d/1nonfcGP7DjIimaCT4vd5MOxsKf-6K3gq8uCc0sCJ7Ks/edit
